### PR TITLE
show line changes

### PR DESCRIPTION
**Pull request by matikin9**
Display line changes data.  Change implementation to just show the Details column instead of the other 3 columns.  Update the schedule PDF linking.

Doesn't show stop changes yet because those updates are not yet merged.

### CODE REVIEW

**Comment by matikin9** [comment]
Note: to get the dropdown selections for testing, go to `index.html` and un-comment out these lines:

image

**Comment by albertkun** [comment]
@matikin9 thanks for the heads about bout the `index.html`! i was wondering how to get the drop downs to show up!

**Comment by albertkun** [comment]
@matikin9 I tested a few lines and found some issues in 2 out of 4... Will continue testing, but can you look into these?

**Line 165**
What is the Vanowen and Mall stop? 
image

**Line 656**
It says owl changes? But shouldn't it be "service replaced"?
image

Am I missing something?
image

**Comment by matikin9** [comment]
@albertkun OH! The new stop changes hadn't been merged into this branch yet so the stop change data would have been off.

Now that those changes are in the dev branch, i've merged them in.  Can you try again?

**Pull request merged**
